### ISSUE TITLE
undefined 'statusCode' error

### ISSUE THREAD

**Issue by mikegilchrist** [masterT/ultimate-guitar-scraper#3]
I get the following error on Ubuntu 16.04
```
> ultimate-guitar-scraper@0.3.0 test /home/user/Personal/Guitar/ultimate-guitar-scraper
> jasmine

Started
........../home/user/Personal/Guitar/ultimate-guitar-scraper/spec/ultimate_guitar_scraper_spec.js:146
      expect(response.statusCode).toBe(200);
                     ^

TypeError: Cannot read property 'statusCode' of undefined
    at /home/user/Personal/Guitar/ultimate-guitar-scraper/spec/ultimate_guitar_scraper_spec.js:146:22
    at Request._callback (/home/user/Personal/Guitar/ultimate-guitar-scraper/lib/index.js:12:7)
    at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
    at emitNone (events.js:72:20)
```
npm ERR! Test failed.  See above for more details.

This appears to be related to delays in the internet connection.

[](http://stackoverflow.com/questions/29752225/http-statuscode-sometimes-undefined)

**Comment by masterT** [comment]
What is your node version ? Did you ran `npm test` or `jasmine`?

**Comment by masterT** [comment]
@mikegilchrist I was able to reproduce the error and I dug up in the spec. It is caused by the `page`param in the spec's query:

```js
{
  bandName: 'Black Keys',
  songName: 'Little Black Submarines',
  type: ['video lessons', 'tabs', 'chords', 'bass tabs', 'guitar pro tabs', 'power tabs', 'drum tabs', 'ukulele chords'],
  page: 3
};
```

This query generates this [URL](https://www.ultimate-guitar.com/search.php?band_name=Black+Keys&song_name=Little+Black+Submarines&type%5B%5D=100&type%5B%5D=200&type%5B%5D=300&type%5B%5D=400&type%5B%5D=500&type%5B%5D=600&type%5B%5D=700&type%5B%5D=800&page=3&view_state=advanced&tab_type_group=text&app_name=ugt&order=myweight&version_la=) which has no results.

This was because when I wrote the specs, *Ultimate Guitar* returned the last page of results for any page params that was higher than the real number of page.

**Comment by masterT** [comment]
@mikegilchrist I publish the `version 0.3.1` with this issue fixed! 😄

**Comment by mikegilchrist** [comment]
Sorry about not responding, it's been hectic on this end.  Thanks for digging 
in and recreating the bug.  I will try the updated version this weekend.

Best,

Mike

-----------------------------------------------------
Dept. of Ecology & Evolutionary Biology
Office Location: 439 Hesler Biology Building
Mailing Address: 569 Dabney Hall
		 University of Tennessee
		 Knoxville, TN 37996-1610
Web page: 	 http://eeb.bio.utk.edu/peopletwo/michael-gilchrist/
Calendar:	 http://www.tiem.utk.edu/~mikeg/calendar.html
-----------------------------------------------------

**Comment by masterT** [comment]
It was a pleasure 👍 !
